# For more info see https://github.com/nodejs/nodejs.org/blob/master/locale/en/docs/guides/nodejs-docker-webapp.md
version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: apidb
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8888:8080
  node:
    user: "node"
    working_dir: /home/node/app
    #If you need to create your image use code below (change config image, expose port or etc.)
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #image: "aandolg/nodejs:latest"
    #command: npm run watch-server
    #Use code below bu default
    image: node:8
    command: bash -c "npm install && npm run watch-server"
    volumes:
      - ./:/home/node/app
    depends_on:
      - db
    ports:
      - 3000:3000
